version: "3"
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - my-network

  orderdb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - my-network

  cartdb:
    image: mongo
    ports:
      - "27018:27017"
    networks:
      - my-network

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - "29092:9092"
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - my-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    networks:
      - my-network

networks:
  my-network:

volumes:
  postgres-data: